---
title: "Flexible Infrastructure for Mass Spectrometry Data"
author:
  - name: Laurent Gatto
    affil: 1
    orcid: "0000-0002-1520-2268"
  - name: Johannes Rainer
    affil: 2
    orcid: "0000-0002-6977-7147"
  - name: Sebastian Gibb
    affil: 3
    orcid: "0000-0001-7406-4443"
affiliation:
  - num: 1
    address: Computational Biology and Bioinformatics Group, de Duve Institute, UCLouvain
  - num: 2
    address: Institute for Biomedicine, Eurac Research
  - num: 3
    address: Department of Anaesthesiology and Intensive Care, University Medicine Greifswald
poster_width: "841mm"
poster_height: "1189mm"
column_numbers: 2
logoleft_name: https&#58;//raw.githubusercontent.com/rformassspectrometry/stickers/master/Spectra/Spectra.png
logoright_name: https&#58;//raw.githubusercontent.com/rformassspectrometry/stickers/master/logo/R4MassSpec-logo.png
bibliography:
  - rpackages.bib
link-citations: true
csl: nature.csl
output:
  posterdown::posterdown_html:
    self_contained: false
---

```{r environment, results = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
Sys.setenv(LANGUAGE = "en")
library("Spectra")

# sudo su apt install mono-devel nuget
# BiocManager::install("cpanse/MsBackendRawFileReader@Bioc3.10")
library("MsBackendRawFileReader")

bkdPkgs <- c("Spectra", "MsBackendRawFileReader")
```

```{r citations, results = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
packagesToCite <- bkdPkgs
bib <- unlist(lapply(packagesToCite, function(x)toBibtex(citation(x))))
bib[grepl("Manual\\{", bib)] <- paste0("@Manual{", packagesToCite, ",")
writeLines(bib, "rpackages.bib")
```

```{r pkgcontent, echo = FALSE, message = FALSE, warning = FALSE}
pkgContent <- ls("package:Spectra")
backendClassNames <- pkgContent[grep("MsBackend.+", pkgContent)]
backendClasses <- lapply(backendClassNames, new)
```

```{r backendtable, echo = FALSE}
classTbl <- data.frame(
    class = backendClassNames,
    storage = ifelse(
        grepl("DataFrame", backendClassNames), "in-memory", "on-disk"
    ),
    writeable = ifelse(!sapply(backendClasses, isReadOnly), "yes", "no")
)

knitr::kable(classTbl)
```

[rformassspectrometry/Spectra](https://github.com/rformassspectrometry/Spectra)

# References
